stages:
  - linting
  - building

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  FASTLANE_OPT_OUT_USAGE: "YES"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

before_script:
  - eval "$(rbenv init - zsh)"
  - brew bundle
  - bundle install

.base: &base_job
  tags:
    - pavelosipov-homebook-runner

lint_app:
  <<: *base_job
  stage: linting
  script:
    - bundle exec rubocop
    - bundle exec fastlane ios lint

build_and_deploy_app:
  <<: *base_job
  stage: building
  script:
    - |
      set -o pipefail && \
      xcodebuild IDEBuildOperationMaxNumberOfConcurrentCompileTasks=12 archive \
      -project "PodlodkaFiles.xcodeproj" \
      -scheme "PodlodkaFiles" \
      -configuration "Release" \
      -destination "generic/platform=iOS" \
      -archivePath "build/app/PodlodkaFiles.xcarchive" \
      CODE_SIGNING_REQUIRED=YES \
      CODE_SIGNING_ALLOWED=YES | xcbeautify
    - |
      bundle exec fastlane ios distribute_app \
      ipa_path:"build/app/PodlodkaFiles.ipa" \
      dsym_path:"build/app/PodlodkaFiles.dSYM.zip" \
      api_token:"${APPCENTER_API_TOKEN}"
