analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_assert
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - identical_operands
  - implicit_return
  - last_where
  - legacy_objc_type
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - private_subject
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

disabled_rules:
  - conditional_returns_on_newline
  - identifier_name
  - inclusive_language
  - nesting
  - redundant_type_annotation
  - trailing_comma
  - type_contents_order

cyclomatic_complexity:
  - 20
  - 20

file_length:
  warning: 500
  error: 700

function_body_length: 30
function_parameter_count: 6
line_length: 120
type_body_length: 200

large_tuple:
  - 4
  - 4

force_try:
  severity: warning

force_cast:
  severity: warning

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: [T, x, dx, y, dx, z, dz, i, j, k, n, a, b, id, Id]

modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

included:
  - PodlodkaFiles

reporter: "xcode"
